### ISSUE TITLE
Support Autolayout

### ISSUE THREAD

**Issue by ogezue** [Fortyfox/MomentsGallery#2]
Hi,
have you planned to support Autolayout?

This is what I get if I rotate my device.

![simulator screen shot 28 03 2016 13 46 53](https://cloud.githubusercontent.com/assets/2361031/14077431/ac306078-f4eb-11e5-8118-d1a7025d6954.png)

**Comment by melvinbeemer** [comment]
Autolayout should definitely be supported. I'll work on it, thanks!
